### ISSUE TITLE
add menu items to report bug/send suggestions

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#109]
Option 1: Direct the user to github issue pages and let the user file the issue on github.
(disadvantage: github account could be required for the user)
Option 2: Create UI in genotet that collects the bug/suggestion, and then auto file the bug/suggestion on github with github API.

**Comment by yubowenok** [comment]
Was option 1 resolved by #114? @djasmine . If so you can temporarily close this. In the future if you wnat to add option 2 you can reopen the issue.

**Comment by djasmine** [comment]
Solved option 1.
