### ISSUE TITLE
server may not want to error when (data, description) mismatch

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#113]
Right now the server errors when it cannot find a corresponding description for a dataset. Suggested:
- When data file is present, but description is missing, we can consider description to be empty string.
- When description file is present, but data file is missing, we can ignore the description file.

**Comment by djasmine** [comment]
Because we use description file to store both data name and description, we need to find it for the data. Or just return empty data name?

**Comment by yubowenok** [comment]
Umm I think empty data name might be better than letting the server error and get stalled.
