### ISSUE TITLE
let server auto log to files named by the server's starting date

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#138]
say we run **node server/server.js** on 2/25. The server should create a file automatically at log/server_022516.log and write to it. If that file exists, then we can do log/server_022516_2.log and so on.

For the simplest you may write a bash script that does

``` js
# start.sh
nohup node --max-old-space-size=8192 server/server.js &>{log/date.log}
```

So every time you only need ./start.sh

**Comment by djasmine** [comment]
finished
