### ISSUE TITLE
large error for storing float?

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#44]
For a given floating number such as 0.0593648, the current bcwig file written will read out 0.05936479941010475 on my machine. This is a relative error around 1E-8. But I don't see any computation involved as we are just writing the floating number to files and read it out. 

I'm not sure what is the exact cause of this. Maybe we can try using double instead of float. Worth an investigation.

**Comment by djasmine** [comment]
I used double and fixed this issue.
