### ISSUE TITLE
number of binding samples

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#45]
The current binding sampling implementation samples constantly 1000 sampled points.

We may need to:
- When there are very few raw data points available within the range, return the raw data points instead.
- Support the numSamples query parameter, which will be set to number of pixels (as indicated in [wiki](https://github.com/ViDA-NYU/genotet/wiki/Server-Queries-Documentation)).

**Comment by djasmine** [comment]
I enabled the numSamples parameter. But for general, we return several same length intervals as the result. When the number of data points is small, should I return data points with different lengths?

**Comment by yubowenok** [comment]
Yes if you are not sampling you can return unevenly distributed points.

**Comment by yubowenok** [comment]
Was this done? @djasmine
