### ISSUE TITLE
parsed bed data does not have labels stored

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#47]

**Comment by yubowenok** [comment]
besides the bed query is not using the correct query paramter. there is no "file" argument but "bedName" according to wiki...

**Comment by liana-yang** [comment]
I am using bed query now and I do not understand the file path: var dir = bedPath + bedName + '_chr/' + bedName + '_' + chr; (line 46) Besides, I do not know what the bedName look like. Does it have file type suffix or not? @djasmine Could you please give more explanation about line 46 and an example of the correct parameters to use this query? Thank you very much!

**Comment by djasmine** [comment]
fixed
