### ISSUE TITLE
Change the way of reading TFA files from binary file (.bin) to text file.

### ISSUE THREAD

**Issue by liana-yang** [ViDA-NYU/genotet#81]
expression.readTFAmat_ reads TFA binary files now. It should be changed to read TFA text file.

**Comment by djasmine** [comment]
There are some problems regarding to TFA files. For storage and uploading, are there differences between TFA matrix and normal matrix files? For listed files, I always read them as matrix files. Or I should not list the TFA files during view creation. What is the relationship between them? And how should I deal with them for storage, listing and uploading. @yubowenok

**Comment by yubowenok** [comment]
- TFA files are in a same format as matrices. But they are TWO types of
  files.
- You should not list TFA files while listing matrices.
- We will add TFA file upload/selection after the release, as it is a
  unique type of files.

**Comment by djasmine** [comment]
fixed
