### ISSUE TITLE
Network gene manipulation doesn't work correctly.

### ISSUE THREAD

**Issue by liana-yang** [ViDA-NYU/genotet#89]
It doesn't work well when input both text and regex. 
1. Regex doesn't match correctly.
2. Adds or updates node with empty gene name label sometimes.

I just found these two bugs and didn't test too much manipulations. Please test carefully and consider cases as much as possible before merging. Thanks.

**Comment by liana-yang** [comment]
Sorry, I didn't sync your latest two pull requests this afternoon. I will update this issue after sync later.

**Comment by yubowenok** [comment]
Confirmed.
![image](https://cloud.githubusercontent.com/assets/1314429/12772295/023e0286-c9fe-11e5-9a26-9146379de7ba.png)
- add "irf" in text mode -> node appearing without label
- remove "irf" in regex mode -> node "irf4" not deleted

**Comment by djasmine** [comment]
Fixed
